### ISSUE TITLE
Push latest version (0.3.0) to RubyGems

### ISSUE THREAD

**Issue by jethrodaniel** [cameronsutter/odyssey#15]
Seems like this gem wasn't pushed to RubyGems on the last version bump.

```
 λ git show  54316ce7bfc068a
commit 54316ce7bfc068a89138b2a738fea58834858784
Author: Michael Lahnert <michael.lahnert@ipvs.uni-stuttgart.de>
Date:   Wed Dec 19 17:42:38 2018 +0100

    Bump version

diff --git a/lib/odyssey/version.rb b/lib/odyssey/version.rb
index d693752..7d4eca8 100644
--- a/lib/odyssey/version.rb
+++ b/lib/odyssey/version.rbhttps://rubygems.org/gems/odyssey/
@@ -1,3 +1,3 @@
 module Odyssey
-  VERSION = "0.2.0"
+  VERSION = "0.3.0"
 end
```

As https://rubygems.org/gems/odyssey/ shows (still on 0.2.0).

@lahnerml Can you push `0.3.0` to rubygems? Thanks!

This fixes https://github.com/cameronsutter/odyssey/issues/13

**Comment by jethrodaniel** [comment]
Also @lahnerml @cameronsutter , I'm open to becoming a maintainer if we need another one.

**Comment by lahnerml** [comment]
@jethrodaniel I think @cameronsutter has to do this.

**Comment by cameronsutter** [comment]
It's been a few years since i've was writing ruby unfortunately. Let me attempt to push the new version and add both of you as owners on the gem

**Comment by cameronsutter** [comment]
@lahnerml @jethrodaniel I'll need your rubygems.org email addresses to add you as owners. DM me on twitter `@camsutter` or email me `cameronsutter0` gmail

**Comment by cameronsutter** [comment]
Pushed version `0.3.0` to rubygems \o/
