### ISSUE TITLE
ETA for publishing v0.2.0 to RubyGems?

### ISSUE THREAD

**Issue by danbernier** [cameronsutter/odyssey#7]
Hello,

First, thanks for making this gem.

It looks like 0.1.8 was published to rubygems.org in June 2013, but 0.2.0 is on github/master. What's the ETA for getting 0.2.0 out to rubygems.org? Anything I can do to help?

**Comment by cameronsutter** [comment]
Oh I'm sorry about the delay. I totally spaced that part. I'll have it
published sometime next week

**Comment by danbernier** [comment]
Sweet, thank you so much!

**Comment by cameronsutter** [comment]
Pushed! Enjoy
