### ISSUE TITLE
Please Release Latest (2018-03-30) to RubyGems

### ISSUE THREAD

**Issue by ylg** [cameronsutter/odyssey#9]
Since bundler's handling of git-sourced gems is so painful and the require_all bug #8 is a bit of a showstopper, it'd be great to see that make it over to rubygems.

**Comment by cameronsutter** [comment]
Sorry it's taken me so long to get back to you, @ylg. Can I add you to the project and let you take care of this? I've been really focused on another project lately.

**Comment by cameronsutter** [comment]
@ylg pushed version `0.3.0` to RubyGems \o/
